language: java
jdk:
  - oraclejdk8
script:
  - mvn install -DskipTests=true
  - mvn test jacoco:report coveralls:report -Dmaven.javadoc.skip=true
after_success:
  - mvn package
addons:
  artifacts:
    paths:
      - $HOME/target/*.jar
